temp<- tempfile()
download.file("https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip")
library(data.table)
data<- read.table(unz(temp,"exdata%2Fdata%2Fhousehold_power_consumption.zip"),skip=1,sep=";")
unlink(temp)
names(data)<- c("date","time","global_active_power","global_reactive_power","voltage","global_intensity","sub_metering1","sub_metering2","submetering3")
subdata<- subset(data,data$date=="01/02/2007" | data$date=="02/02/2007")
png("plot1.png",width=480,height = 480)
hist(as.numeric(as.character(subdata$global_active_power)),col="red",main = "Global Active Power",xlab="Global ACtive Power(kilowatts)",ylab="Frequency")
dev.off()
